### ISSUE TITLE
No Error Handlers

### ISSUE THREAD

**Issue by ebarthur** [amoakodomson25/School-Grading-System#2]
In your code, if Fees_Paid ==  {any other input aside 'y'}, the code will still display the else statement even tho input was wrong. I suggest you wrap the code in a function and create one to call-back "Have you paid your fees?" when input is wrong.

**Comment by amoakodomson25** [comment]
I am working on it right now. Thank you.

**Comment by amoakodomson25** [comment]
Fixed. Thank you once again.
